#pragma once

#include "stdafx.h"

enum class DeviceType
{
    /// <summary>
    /// Glare shield
    /// </summary>
    Glare = 1,
    /// <summary>
    /// Pedestal.
    /// </summary>
    Pedestal = 2,
    /// <summary>
    /// Overhead panel
    /// </summary>
    Overhead = 3,
    /// <summary>
    /// Captain's MCDU
    /// </summary>
    MCDU1 = 4,
    /// <summary>
    /// First Officer's MCDU
    /// </summary>
    MCDU2 = 5,
    /// <summary>
    /// MD80 Mode Control Panel
    /// </summary>
    MD80MCP = 6,
    /// <summary>
    /// Throttle Quadrant
    /// </summary>
    TQ = 7,
    /// <summary>
    /// Main instrument panel
    /// </summary>
    Mip = 8,
    /// <summary>
    /// Clock
    /// </summary>
    CLOCK = 9,
    /// <summary>
    /// ECAM
    /// </summary>
    ECAM = 10,
    /// <summary>
    /// Lower pedestal
    /// </summary>
    LOWERPED = 11,
    /// <summary>
    /// Transponder
    /// </summary>
    ATC = 12,
    /// <summary>
    /// Captain's Radio Management Panel
    /// </summary>
    RMP1 = 13,
    /// <summary>
    /// First Officer's Radio Management Panel
    /// </summary>
    RMP2 = 14,
    /// <summary>
    /// Third Radio Management Panel
    /// </summary>
    RMP3 = 15,
    /// <summary>
    /// Captain's Audio Control Panel
    /// </summary>
    ACP1 = 16,
    /// <summary>
    /// First Officer's Audio Control Panel
    /// </summary>
    ACP2 = 17,
    /// <summary>
    /// Third Audio Control Panel
    /// </summary>
    ACP3 = 18,
    /// <summary>
    /// Refuel Panel
    /// </summary>
    REFUEL = 19
};

enum HardwareSource
{
    /// <summary>
    /// The event is generated by a switch.
    /// </summary>
    Switch,
    /// <summary>
    /// The event is generated by an encoder.
    /// </summary>
    Encoder,
    /// <summary>
    /// The event is generated by an axis.
    /// </summary>
    Axis,
    /// <summary>
    /// The event is generated by an unknown source.
    /// </summary>
    Unknown
};

enum PacketType
{
    HardwareEvent,
    ConnectionStateEvent,
};

enum class Group
{
    /// <summary>
    /// Interior lighting
    /// </summary>
    INTLT,
    /// <summary>
    /// Main instrument panel
    /// </summary>
    MIP,
    /// <summary>
    /// Audio control panel 1
    /// </summary>
    ACP1,
    /// <summary>
    /// Audio control panel 2
    /// </summary>
    ACP2,
    /// <summary>
    /// Audio control panel 3
    /// </summary>
    ACP3,
    /// <summary>
    /// ADIRS
    /// </summary>
    ADIRS,
    /// <summary>
    /// Anti ice
    /// </summary>
    ANTIICE,
    /// <summary>
    /// APU
    /// </summary>
    APU,
    /// <summary>
    /// Transponder
    /// </summary>
    TRANSPONDER,
    /// <summary>
    /// Cabin pressurization
    /// </summary>
    CABINPRESS,
    /// <summary>
    /// Calls management
    /// </summary>
    CALLS,
    /// <summary>
    /// Cargo heat
    /// </summary>
    CARGOHEAT,
    /// <summary>
    /// Cargo smoke
    /// </summary>
    CARGOSMOKE,
    /// <summary>
    /// ECAM
    /// </summary>
    ECAM,
    /// <summary>
    /// Captain's side EFIS
    /// </summary>
    EFISCS,
    /// <summary>
    /// First Officer's side EFIS
    /// </summary>
    EFISFO,
    /// <summary>
    /// Electrical
    /// </summary>
    ELEC,
    /// <summary>
    /// Emergency electrical
    /// </summary>
    EMERELEC,
    /// <summary>
    /// Evacuation system
    /// </summary>
    EVAC,
    /// <summary>
    /// Exterior lighting
    /// </summary>
    EXTLT,
    /// <summary>
    /// Flight control unit
    /// </summary>
    FCU,
    /// <summary>
    /// Flight controls
    /// </summary>
    FCTL,
    /// <summary>
    /// Fuel
    /// </summary>
    FUEL,
    /// <summary>
    /// Ground proximity warning system
    /// </summary>
    GPWS,
    /// <summary>
    /// Lower pedestal
    /// </summary>
    LOWER,
    /// <summary>
    /// Aft overhead
    /// </summary>
    AFT,
    /// <summary>
    /// Oxygen system
    /// </summary>
    OXYGEN,
    /// <summary>
    /// Air conditioning system
    /// </summary>
    AIRCOND,
    /// <summary>
    /// Recorder
    /// </summary>
    RCDR,
    /// <summary>
    /// Radio management panel 1
    /// </summary>
    RMP1,
    /// <summary>
    /// Radio management panel 2
    /// </summary>
    RMP2,
    /// <summary>
    /// Radio management panel 3
    /// </summary>
    RMP3,
    /// <summary>
    /// Signs (seat belt/smoking)
    /// </summary>
    SIGNS,
    /// <summary>
    /// Throttle quadrant
    /// </summary>
    TQ,
    /// <summary>
    /// Ventilation
    /// </summary>
    VENTILATION,
    /// <summary>
    /// Glare wings
    /// </summary>
    WINGS,
    /// <summary>
    /// Fire suppression
    /// </summary>
    FIRE,
    /// <summary>
    /// Hydraulics
    /// </summary>
    HYD,
    /// <summary>
    /// Captain's MCDU
    /// </summary>
    MCDUCS,
    /// <summary>
    /// First officer's MCDU
    /// </summary>
    MCDUFO,
    /// <summary>
    /// Lights (exterior)
    /// </summary>
    LIGHT,
    /// <summary>
    /// Engines
    /// </summary>
    ENG,
    /// <summary>
    /// Refuel
    /// </summary>
    REFUEL,
    /// <summary>
    /// Pushback
    /// </summary>
    PUSHBACK,
    /// <summary>
    /// Backlight
    /// </summary>
    BACKLIGHT,
    /// <summary>
    /// The clock
    /// </summary>
    CLOCK
};
